detectors:
  Attribute:
    enabled: false
  IrresponsibleModule:
    enabled: false
  UtilityFunction:
    public_methods_only: true
    exclude:
      - Proofer::Vendor::VendorBase
      - Proofer::Vendor::Mock#coerce_vendor_applicant
  FeatureEnvy:
    exclude:
      - Proofer::Vendor::VendorBase
      - Proofer::Question#choices_as_hash
  ManualDispatch:
    exclude:
      - Proofer::Applicant#initialize
  NilCheck:
    exclude:
      - Proofer::Vendor::VendorBase
      - Proofer::Result#exception?
  ControlParameter:
    exclude:
      - Proofer::Vendor::Mock#submit_phone
      - Proofer::Base#proof
      - Proofer::Base#stage
      - Proofer::Base#vendor_name
  TooManyStatements:
    max_statements: 8
  TooManyMethods:
    max_methods: 20
  TooManyInstanceVariables:
    exclude:
      - Proofer::Base
      - Proofer::Result
  InstanceVariableAssumption:
    exclude:
        - 'Proofer::Base'
