# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the Ruby version you desire here
      - image: circleci/ruby:2.5.1
        environment:
          CC_TEST_REPORTER_ID: b492957f6df97f9c3079b494cf578be9ec52420edf592293f471c111217efca6

    working_directory: ~/identity-proofer-gem

    steps:
      - checkout

      - restore-cache:
          key: identity-proofer-gem-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      # Store bundle cache
      - save-cache:
          key: identity-proofer-gem-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Install Code Climate Test Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: Run Tests
          command: |
            mkdir /tmp/test-results
            ./cc-test-reporter before-build
            bundle exec rake test

      - run:
          name: Upload Test Results to Code Climate
          command:
            ./cc-test-reporter format-coverage -t simplecov $CIRCLE_ARTIFACTS/coverage/.resultset.json
            ./cc-test-reporter upload-coverage

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
