require_relative 'proofer/version'
require_relative 'proofer/agent'
require_relative 'proofer/applicant'
require_relative 'proofer/question_set'
require_relative 'proofer/unknown_vendor_response'
require_relative 'proofer/resolution'
require_relative 'proofer/confirmation'
